name: Tests

on: push

jobs:
  tests:
    name: Execute Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Open application
        run: |
          start "AppForWorkflow\CoinCollectorStandalone.exe"
          cd CoinCollector.Tests
          set ALTSERVER_PORT=13000
          echo %ALTSERVER_PORT%
          set ALTSERVER_HOST="127.0.0.1"
      
      - name: Run tests from InputActionsTests
        run: |
          dotnet test --filter=InputActionsTests