name: Tests

on: push

jobs:
  tests:
    name: Execute Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install AltTester Driver
        run: |
          cd CoinCollector.Tests
          dotnet add package AltTester-Driver --version 1.8.0
        shell: bash

      - name: Open application
        run: |
          start AppForWorkflow/CoinCollectorStandalone.exe
          set ALTSERVER_PORT=13000
          set ALTSERVER_HOST="127.0.0.1"
        shell: bash
      
      - name: Run tests from InputActionsTests
        run: |
          cd CoinCollector.Tests
          dotnet test --filter=InputActionsTests
        shell: bash